### PR TITLE
Added `invoiceImmediately` and `disableProrations` parameters to `updateSubscriptionItem` function.

### PR DESCRIPTION
**Pull request by keyding**
Added `invoiceImmediately` and `disableProrations` parameters to `updateSubscriptionItem` function.

### CODE REVIEW

**Comment by elie222** [comment]
Looking forward to seeing this added.

**Review by brankoconjic — APPROVED** [review]
Looks good.

**Comment by elie222** [comment]
Has a deprecated warning. Because the function has the same name:

CleanShot 2024-02-29 at 10 48 54@2x

**Comment by elie222** [comment]
It's fine when I use it though:

CleanShot 2024-02-29 at 10 49 39@2x

**Pull request merged**
